base.archivesName = "trackercompass-api"

loom {
    runConfigs.clear()
    mods {
        "trackercompass-api" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "net.casualchampionships:arcade-utils:${project.arcade_version}"
    compileOnly "eu.pb4:placeholder-api:${project.placeholder_api_version}"
    compileOnly "eu.pb4:predicate-api:${project.predicate_api_version}"
}
